/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmandiri;

import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class transaksi extends javax.swing.JFrame {
    
    String str, str1;
    int t,s,tab=500000;
    
    public transaksi() {
        initComponents();
        tSaldo.setText(""+tab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tSaldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tJumlah = new javax.swing.JTextField();
        bTrans = new javax.swing.JButton();
        bSetor = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        bTarik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSAKSI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 66));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Saldo ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 60, 30));

        tSaldo.setEditable(false);
        jPanel1.add(tSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 60, 30));
        jPanel1.add(tJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 170, 40));

        bTrans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bTrans.setText("Transfer");
        bTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransActionPerformed(evt);
            }
        });
        jPanel1.add(bTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 110, 50));

        bSetor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bSetor.setText("Setor");
        bSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetorActionPerformed(evt);
            }
        });
        jPanel1.add(bSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 120, 50));

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 90, 40));

        bTarik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bTarik.setText("Tarik");
        bTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTarikActionPerformed(evt);
            }
        });
        jPanel1.add(bTarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetorActionPerformed
        // TODO add your handling code here:
        
        String uang = tSaldo.getText();
        String tabung = tJumlah.getText().toString();
        
        s= Integer.parseInt(uang);
        int hasil = Integer.parseInt(tabung);
        int total = s+hasil;
        
        if(s%100!=0)
            JOptionPane.showMessageDialog(null, "Mesin ATM MANDIRI tidak menerima uang koin \n Silahkan Ulangi Kembali !", "Transaksi Gagal",0);
        else if(s<10000)
            JOptionPane.showMessageDialog(null, "Besaran minimal setor tunai adalah Rp.10.000,00", "ERROR",0);
        else if(s>=10000)
            tSaldo.setText(""+total);
    }//GEN-LAST:event_bSetorActionPerformed

    private void bTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTarikActionPerformed
        // TODO add your handling code here:
       String tabung = tSaldo.getText();
       
        t= Integer.parseInt(tJumlah.getText());
        int hasil = Integer.parseInt(tSaldo.getText());
        int total = hasil-t;
        
        if(t%100!=0)
            JOptionPane.showMessageDialog(null, "Mesin ATM MANDIRI tidak menerima uang koin \nSilahkan ulagi Lagi", "Transaksi Gagal",0);
        else{
            if(t>tab)
            JOptionPane.showMessageDialog(null, "Saldo anda tidak mencukupi \nMohon melakukan penyetoran", "Transaksi Gagal",0); 
            else if(t<10000)
            JOptionPane.showMessageDialog(null, "Besaran minimal pengambilan tunai adalah Rp.10.000,00", "Transaksi Gagal",0);
            else{
                tSaldo.setText(""+total);
                if (tab<=10000)
                {
                    JOptionPane.showMessageDialog(null,"Saldo minimal RP 10.000,00 , Mohon melakukan penyetoran untuk menghindari penutupan akun", "CAUTION", 2);
                }
            }
        }
    }//GEN-LAST:event_bTarikActionPerformed

    private void bTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransActionPerformed
        // TODO add your handling code here:
        String tabung = tSaldo.getText();
       
        t= Integer.parseInt(tJumlah.getText());
        int hasil = Integer.parseInt(tSaldo.getText());
        int total = hasil-t;
        
        if(t%100!=0)
            JOptionPane.showMessageDialog(null, "Mesin ATM MANDIRI tidak menerima uang koin \nSilahkan ulagi Lagi", "Transaksi Gagal",0);
        else{
            if(t>tab)
            JOptionPane.showMessageDialog(null, "Saldo anda tidak mencukupi \nMohon melakukan penyetoran", "Transaksi Gagal",0); 
            else if(t<50000)
            JOptionPane.showMessageDialog(null, "Besaran minimal transfer tunai adalah Rp.50.000,00", "Transaksi Gagal",0);
            else{
                tSaldo.setText(""+total);
                if (tab<=50000)
                {
                    JOptionPane.showMessageDialog(null,"Saldo minimal harus RP 50.000,00 , Mohon melakukan penyetoran untuk menghindari penutupan akun", "CAUTION", 2);
                }
            }
        }
    }//GEN-LAST:event_bTransActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
       JOptionPane.showConfirmDialog(null,"Anda ingin keluar?","ATM MANDIRI",JOptionPane.YES_NO_OPTION, 3);
       this.dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSetor;
    private javax.swing.JButton bTarik;
    private javax.swing.JButton bTrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tSaldo;
    // End of variables declaration//GEN-END:variables
}
